### PR TITLE
fixed issue when SWAL is loaded in head section of page

### PR DESCRIPTION
**Pull request by Mart-Bogdan**
There were error, if sweetalert's < script > is being loaded from head section of HTM

### CODE REVIEW

**Comment by caseyWebb** [comment]
Thanks!

**Comment by Mart-Bogdan** [comment]
@caseyWebb can you explain me, what's the difference between /dev/modules/utils.js and /lib/modules/utils.js I'm pretty new at frontend development.

It's seems that gulp is building dist from /dev/modules and runs tests from /lib/modules
But /lib/modules isn't auto generated from dev..

**Comment by caseyWebb** [comment]
The lib dir is created by processing the dev dir through babel — so that you could require individual files from it w/o having to run babel on your dependencies.

**Comment by Mart-Bogdan** [comment]
Hello, @caseyWebb , how do you think, won't it be better to use **document.body** instead, I guess it would be faster, as getElementsByTagName searches among all DOM nodes. 

https://developer.mozilla.org/en-US/docs/Web/API/Document/body

**Pull request merged**
